# golangci-lint configuration for version 2
# See https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck      # Check for unchecked errors (default)
    - govet         # Reports suspicious constructs (default)
    - ineffassign   # Detect ineffectual assignments (default)
    - staticcheck   # Advanced static analysis (default)
    - unused        # Check for unused code (default)
    - misspell      # Spell checking
    - unconvert     # Remove unnecessary conversions
    - gocyclo       # Cyclomatic complexity
    - goconst       # Find repeated strings
    - bodyclose     # HTTP response body checks
    - whitespace    # Whitespace detection

issues:
  max-per-linter: 50
  max-same: 3
