// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/api/v1/switcher.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResolveRequest contains a DNS query.
type ResolveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The domain name to resolve.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The DNS record type (A, AAAA, CNAME, etc.).
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ResolveResponse contains the DNS resolution result.
type ResolveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resolved records.
	Records []*DNSRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// Which resolver was used.
	ResolverUsed string `protobuf:"bytes,2,opt,name=resolver_used,json=resolverUsed,proto3" json:"resolver_used,omitempty"`
	// Whether the request pattern matched.
	RequestMatched bool `protobuf:"varint,3,opt,name=request_matched,json=requestMatched,proto3" json:"request_matched,omitempty"`
	// Whether the CNAME pattern matched.
	CnameMatched bool `protobuf:"varint,4,opt,name=cname_matched,json=cnameMatched,proto3" json:"cname_matched,omitempty"`
	// The matched request pattern (if any).
	MatchedPattern string `protobuf:"bytes,5,opt,name=matched_pattern,json=matchedPattern,proto3" json:"matched_pattern,omitempty"`
	// The matched CNAME pattern (if any).
	CnamePattern string `protobuf:"bytes,6,opt,name=cname_pattern,json=cnamePattern,proto3" json:"cname_pattern,omitempty"`
	// The DNS response code.
	Rcode         string `protobuf:"bytes,7,opt,name=rcode,proto3" json:"rcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetRecords() []*DNSRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ResolveResponse) GetResolverUsed() string {
	if x != nil {
		return x.ResolverUsed
	}
	return ""
}

func (x *ResolveResponse) GetRequestMatched() bool {
	if x != nil {
		return x.RequestMatched
	}
	return false
}

func (x *ResolveResponse) GetCnameMatched() bool {
	if x != nil {
		return x.CnameMatched
	}
	return false
}

func (x *ResolveResponse) GetMatchedPattern() string {
	if x != nil {
		return x.MatchedPattern
	}
	return ""
}

func (x *ResolveResponse) GetCnamePattern() string {
	if x != nil {
		return x.CnamePattern
	}
	return ""
}

func (x *ResolveResponse) GetRcode() string {
	if x != nil {
		return x.Rcode
	}
	return ""
}

// DNSRecord represents a DNS record.
type DNSRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Record name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Record type.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Record TTL.
	Ttl uint32 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Record value/data.
	Value         string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{2}
}

func (x *DNSRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DNSRecord) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *DNSRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// GetConfigRequest is empty - no parameters needed.
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{3}
}

// GetConfigResponse contains the current configuration.
type GetConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request patterns.
	RequestPatterns []string `protobuf:"bytes,1,rep,name=request_patterns,json=requestPatterns,proto3" json:"request_patterns,omitempty"`
	// CNAME patterns.
	CnamePatterns []string `protobuf:"bytes,2,rep,name=cname_patterns,json=cnamePatterns,proto3" json:"cname_patterns,omitempty"`
	// Request resolver address.
	RequestResolver string `protobuf:"bytes,3,opt,name=request_resolver,json=requestResolver,proto3" json:"request_resolver,omitempty"`
	// Explicit resolver address.
	ExplicitResolver string `protobuf:"bytes,4,opt,name=explicit_resolver,json=explicitResolver,proto3" json:"explicit_resolver,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigResponse) GetRequestPatterns() []string {
	if x != nil {
		return x.RequestPatterns
	}
	return nil
}

func (x *GetConfigResponse) GetCnamePatterns() []string {
	if x != nil {
		return x.CnamePatterns
	}
	return nil
}

func (x *GetConfigResponse) GetRequestResolver() string {
	if x != nil {
		return x.RequestResolver
	}
	return ""
}

func (x *GetConfigResponse) GetExplicitResolver() string {
	if x != nil {
		return x.ExplicitResolver
	}
	return ""
}

// UpdatePatternsRequest contains new patterns.
type UpdatePatternsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new patterns to set.
	Patterns      []string `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatternsRequest) Reset() {
	*x = UpdatePatternsRequest{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatternsRequest) ProtoMessage() {}

func (x *UpdatePatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatternsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePatternsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePatternsRequest) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

// UpdatePatternsResponse indicates the result of the update.
type UpdatePatternsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the update was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if unsuccessful.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// The current patterns after update.
	Patterns      []string `protobuf:"bytes,3,rep,name=patterns,proto3" json:"patterns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatternsResponse) Reset() {
	*x = UpdatePatternsResponse{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatternsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatternsResponse) ProtoMessage() {}

func (x *UpdatePatternsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatternsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePatternsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePatternsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePatternsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdatePatternsResponse) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

// GetStatsRequest is empty - no parameters needed.
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{7}
}

// GetStatsResponse contains statistics.
type GetStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total requests processed.
	TotalRequests uint64 `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	// Requests by resolver.
	RequestsByResolver map[string]uint64 `protobuf:"bytes,2,rep,name=requests_by_resolver,json=requestsByResolver,proto3" json:"requests_by_resolver,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Pattern match counts.
	PatternMatches map[string]uint64 `protobuf:"bytes,3,rep,name=pattern_matches,json=patternMatches,proto3" json:"pattern_matches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// CNAME match counts.
	CnameMatches map[string]uint64 `protobuf:"bytes,4,rep,name=cname_matches,json=cnameMatches,proto3" json:"cname_matches,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Uptime in seconds.
	UptimeSeconds uint64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_v1_switcher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_v1_switcher_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatsResponse) GetTotalRequests() uint64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *GetStatsResponse) GetRequestsByResolver() map[string]uint64 {
	if x != nil {
		return x.RequestsByResolver
	}
	return nil
}

func (x *GetStatsResponse) GetPatternMatches() map[string]uint64 {
	if x != nil {
		return x.PatternMatches
	}
	return nil
}

func (x *GetStatsResponse) GetCnameMatches() map[string]uint64 {
	if x != nil {
		return x.CnameMatches
	}
	return nil
}

func (x *GetStatsResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

var File_pkg_api_v1_switcher_proto protoreflect.FileDescriptor

const file_pkg_api_v1_switcher_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/api/v1/switcher.proto\x12\x06api.v1\"8\n" +
	"\x0eResolveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x95\x02\n" +
	"\x0fResolveResponse\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.api.v1.DNSRecordR\arecords\x12#\n" +
	"\rresolver_used\x18\x02 \x01(\tR\fresolverUsed\x12'\n" +
	"\x0frequest_matched\x18\x03 \x01(\bR\x0erequestMatched\x12#\n" +
	"\rcname_matched\x18\x04 \x01(\bR\fcnameMatched\x12'\n" +
	"\x0fmatched_pattern\x18\x05 \x01(\tR\x0ematchedPattern\x12#\n" +
	"\rcname_pattern\x18\x06 \x01(\tR\fcnamePattern\x12\x14\n" +
	"\x05rcode\x18\a \x01(\tR\x05rcode\"[\n" +
	"\tDNSRecord\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\x12\n" +
	"\x10GetConfigRequest\"\xbd\x01\n" +
	"\x11GetConfigResponse\x12)\n" +
	"\x10request_patterns\x18\x01 \x03(\tR\x0frequestPatterns\x12%\n" +
	"\x0ecname_patterns\x18\x02 \x03(\tR\rcnamePatterns\x12)\n" +
	"\x10request_resolver\x18\x03 \x01(\tR\x0frequestResolver\x12+\n" +
	"\x11explicit_resolver\x18\x04 \x01(\tR\x10explicitResolver\"3\n" +
	"\x15UpdatePatternsRequest\x12\x1a\n" +
	"\bpatterns\x18\x01 \x03(\tR\bpatterns\"d\n" +
	"\x16UpdatePatternsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1a\n" +
	"\bpatterns\x18\x03 \x03(\tR\bpatterns\"\x11\n" +
	"\x0fGetStatsRequest\"\xb7\x04\n" +
	"\x10GetStatsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x04R\rtotalRequests\x12b\n" +
	"\x14requests_by_resolver\x18\x02 \x03(\v20.api.v1.GetStatsResponse.RequestsByResolverEntryR\x12requestsByResolver\x12U\n" +
	"\x0fpattern_matches\x18\x03 \x03(\v2,.api.v1.GetStatsResponse.PatternMatchesEntryR\x0epatternMatches\x12O\n" +
	"\rcname_matches\x18\x04 \x03(\v2*.api.v1.GetStatsResponse.CnameMatchesEntryR\fcnameMatches\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x1aE\n" +
	"\x17RequestsByResolverEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aA\n" +
	"\x13PatternMatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a?\n" +
	"\x11CnameMatchesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x012\x86\x03\n" +
	"\x19NameserverSwitcherService\x12:\n" +
	"\aResolve\x12\x16.api.v1.ResolveRequest\x1a\x17.api.v1.ResolveResponse\x12@\n" +
	"\tGetConfig\x12\x18.api.v1.GetConfigRequest\x1a\x19.api.v1.GetConfigResponse\x12V\n" +
	"\x15UpdateRequestPatterns\x12\x1d.api.v1.UpdatePatternsRequest\x1a\x1e.api.v1.UpdatePatternsResponse\x12T\n" +
	"\x13UpdateCNAMEPatterns\x12\x1d.api.v1.UpdatePatternsRequest\x1a\x1e.api.v1.UpdatePatternsResponse\x12=\n" +
	"\bGetStats\x12\x17.api.v1.GetStatsRequest\x1a\x18.api.v1.GetStatsResponseB2Z0github.com/steigr/nameserver-switcher/pkg/api/v1b\x06proto3"

var (
	file_pkg_api_v1_switcher_proto_rawDescOnce sync.Once
	file_pkg_api_v1_switcher_proto_rawDescData []byte
)

func file_pkg_api_v1_switcher_proto_rawDescGZIP() []byte {
	file_pkg_api_v1_switcher_proto_rawDescOnce.Do(func() {
		file_pkg_api_v1_switcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_v1_switcher_proto_rawDesc), len(file_pkg_api_v1_switcher_proto_rawDesc)))
	})
	return file_pkg_api_v1_switcher_proto_rawDescData
}

var file_pkg_api_v1_switcher_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_api_v1_switcher_proto_goTypes = []any{
	(*ResolveRequest)(nil),         // 0: api.v1.ResolveRequest
	(*ResolveResponse)(nil),        // 1: api.v1.ResolveResponse
	(*DNSRecord)(nil),              // 2: api.v1.DNSRecord
	(*GetConfigRequest)(nil),       // 3: api.v1.GetConfigRequest
	(*GetConfigResponse)(nil),      // 4: api.v1.GetConfigResponse
	(*UpdatePatternsRequest)(nil),  // 5: api.v1.UpdatePatternsRequest
	(*UpdatePatternsResponse)(nil), // 6: api.v1.UpdatePatternsResponse
	(*GetStatsRequest)(nil),        // 7: api.v1.GetStatsRequest
	(*GetStatsResponse)(nil),       // 8: api.v1.GetStatsResponse
	nil,                            // 9: api.v1.GetStatsResponse.RequestsByResolverEntry
	nil,                            // 10: api.v1.GetStatsResponse.PatternMatchesEntry
	nil,                            // 11: api.v1.GetStatsResponse.CnameMatchesEntry
}
var file_pkg_api_v1_switcher_proto_depIdxs = []int32{
	2,  // 0: api.v1.ResolveResponse.records:type_name -> api.v1.DNSRecord
	9,  // 1: api.v1.GetStatsResponse.requests_by_resolver:type_name -> api.v1.GetStatsResponse.RequestsByResolverEntry
	10, // 2: api.v1.GetStatsResponse.pattern_matches:type_name -> api.v1.GetStatsResponse.PatternMatchesEntry
	11, // 3: api.v1.GetStatsResponse.cname_matches:type_name -> api.v1.GetStatsResponse.CnameMatchesEntry
	0,  // 4: api.v1.NameserverSwitcherService.Resolve:input_type -> api.v1.ResolveRequest
	3,  // 5: api.v1.NameserverSwitcherService.GetConfig:input_type -> api.v1.GetConfigRequest
	5,  // 6: api.v1.NameserverSwitcherService.UpdateRequestPatterns:input_type -> api.v1.UpdatePatternsRequest
	5,  // 7: api.v1.NameserverSwitcherService.UpdateCNAMEPatterns:input_type -> api.v1.UpdatePatternsRequest
	7,  // 8: api.v1.NameserverSwitcherService.GetStats:input_type -> api.v1.GetStatsRequest
	1,  // 9: api.v1.NameserverSwitcherService.Resolve:output_type -> api.v1.ResolveResponse
	4,  // 10: api.v1.NameserverSwitcherService.GetConfig:output_type -> api.v1.GetConfigResponse
	6,  // 11: api.v1.NameserverSwitcherService.UpdateRequestPatterns:output_type -> api.v1.UpdatePatternsResponse
	6,  // 12: api.v1.NameserverSwitcherService.UpdateCNAMEPatterns:output_type -> api.v1.UpdatePatternsResponse
	8,  // 13: api.v1.NameserverSwitcherService.GetStats:output_type -> api.v1.GetStatsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_api_v1_switcher_proto_init() }
func file_pkg_api_v1_switcher_proto_init() {
	if File_pkg_api_v1_switcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_v1_switcher_proto_rawDesc), len(file_pkg_api_v1_switcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_v1_switcher_proto_goTypes,
		DependencyIndexes: file_pkg_api_v1_switcher_proto_depIdxs,
		MessageInfos:      file_pkg_api_v1_switcher_proto_msgTypes,
	}.Build()
	File_pkg_api_v1_switcher_proto = out.File
	file_pkg_api_v1_switcher_proto_goTypes = nil
	file_pkg_api_v1_switcher_proto_depIdxs = nil
}
