// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: pkg/api/v1/switcher.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NameserverSwitcherService_Resolve_FullMethodName               = "/api.v1.NameserverSwitcherService/Resolve"
	NameserverSwitcherService_GetConfig_FullMethodName             = "/api.v1.NameserverSwitcherService/GetConfig"
	NameserverSwitcherService_UpdateRequestPatterns_FullMethodName = "/api.v1.NameserverSwitcherService/UpdateRequestPatterns"
	NameserverSwitcherService_UpdateCNAMEPatterns_FullMethodName   = "/api.v1.NameserverSwitcherService/UpdateCNAMEPatterns"
	NameserverSwitcherService_GetStats_FullMethodName              = "/api.v1.NameserverSwitcherService/GetStats"
)

// NameserverSwitcherServiceClient is the client API for NameserverSwitcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NameserverSwitcherService provides DNS resolution and configuration management.
type NameserverSwitcherServiceClient interface {
	// Resolve performs a DNS lookup following the nameserver-switcher routing logic.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	// GetConfig returns the current configuration.
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// UpdateRequestPatterns updates the request matching patterns.
	UpdateRequestPatterns(ctx context.Context, in *UpdatePatternsRequest, opts ...grpc.CallOption) (*UpdatePatternsResponse, error)
	// UpdateCNAMEPatterns updates the CNAME matching patterns.
	UpdateCNAMEPatterns(ctx context.Context, in *UpdatePatternsRequest, opts ...grpc.CallOption) (*UpdatePatternsResponse, error)
	// GetStats returns current statistics.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type nameserverSwitcherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNameserverSwitcherServiceClient(cc grpc.ClientConnInterface) NameserverSwitcherServiceClient {
	return &nameserverSwitcherServiceClient{cc}
}

func (c *nameserverSwitcherServiceClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, NameserverSwitcherService_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameserverSwitcherServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, NameserverSwitcherService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameserverSwitcherServiceClient) UpdateRequestPatterns(ctx context.Context, in *UpdatePatternsRequest, opts ...grpc.CallOption) (*UpdatePatternsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePatternsResponse)
	err := c.cc.Invoke(ctx, NameserverSwitcherService_UpdateRequestPatterns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameserverSwitcherServiceClient) UpdateCNAMEPatterns(ctx context.Context, in *UpdatePatternsRequest, opts ...grpc.CallOption) (*UpdatePatternsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePatternsResponse)
	err := c.cc.Invoke(ctx, NameserverSwitcherService_UpdateCNAMEPatterns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameserverSwitcherServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, NameserverSwitcherService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameserverSwitcherServiceServer is the server API for NameserverSwitcherService service.
// All implementations must embed UnimplementedNameserverSwitcherServiceServer
// for forward compatibility.
//
// NameserverSwitcherService provides DNS resolution and configuration management.
type NameserverSwitcherServiceServer interface {
	// Resolve performs a DNS lookup following the nameserver-switcher routing logic.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	// GetConfig returns the current configuration.
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// UpdateRequestPatterns updates the request matching patterns.
	UpdateRequestPatterns(context.Context, *UpdatePatternsRequest) (*UpdatePatternsResponse, error)
	// UpdateCNAMEPatterns updates the CNAME matching patterns.
	UpdateCNAMEPatterns(context.Context, *UpdatePatternsRequest) (*UpdatePatternsResponse, error)
	// GetStats returns current statistics.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedNameserverSwitcherServiceServer()
}

// UnimplementedNameserverSwitcherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNameserverSwitcherServiceServer struct{}

func (UnimplementedNameserverSwitcherServiceServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedNameserverSwitcherServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedNameserverSwitcherServiceServer) UpdateRequestPatterns(context.Context, *UpdatePatternsRequest) (*UpdatePatternsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRequestPatterns not implemented")
}
func (UnimplementedNameserverSwitcherServiceServer) UpdateCNAMEPatterns(context.Context, *UpdatePatternsRequest) (*UpdatePatternsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCNAMEPatterns not implemented")
}
func (UnimplementedNameserverSwitcherServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedNameserverSwitcherServiceServer) mustEmbedUnimplementedNameserverSwitcherServiceServer() {
}
func (UnimplementedNameserverSwitcherServiceServer) testEmbeddedByValue() {}

// UnsafeNameserverSwitcherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameserverSwitcherServiceServer will
// result in compilation errors.
type UnsafeNameserverSwitcherServiceServer interface {
	mustEmbedUnimplementedNameserverSwitcherServiceServer()
}

func RegisterNameserverSwitcherServiceServer(s grpc.ServiceRegistrar, srv NameserverSwitcherServiceServer) {
	// If the following call panics, it indicates UnimplementedNameserverSwitcherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NameserverSwitcherService_ServiceDesc, srv)
}

func _NameserverSwitcherService_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameserverSwitcherServiceServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameserverSwitcherService_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameserverSwitcherServiceServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameserverSwitcherService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameserverSwitcherServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameserverSwitcherService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameserverSwitcherServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameserverSwitcherService_UpdateRequestPatterns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePatternsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameserverSwitcherServiceServer).UpdateRequestPatterns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameserverSwitcherService_UpdateRequestPatterns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameserverSwitcherServiceServer).UpdateRequestPatterns(ctx, req.(*UpdatePatternsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameserverSwitcherService_UpdateCNAMEPatterns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePatternsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameserverSwitcherServiceServer).UpdateCNAMEPatterns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameserverSwitcherService_UpdateCNAMEPatterns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameserverSwitcherServiceServer).UpdateCNAMEPatterns(ctx, req.(*UpdatePatternsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameserverSwitcherService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameserverSwitcherServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NameserverSwitcherService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameserverSwitcherServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NameserverSwitcherService_ServiceDesc is the grpc.ServiceDesc for NameserverSwitcherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NameserverSwitcherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.NameserverSwitcherService",
	HandlerType: (*NameserverSwitcherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _NameserverSwitcherService_Resolve_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _NameserverSwitcherService_GetConfig_Handler,
		},
		{
			MethodName: "UpdateRequestPatterns",
			Handler:    _NameserverSwitcherService_UpdateRequestPatterns_Handler,
		},
		{
			MethodName: "UpdateCNAMEPatterns",
			Handler:    _NameserverSwitcherService_UpdateCNAMEPatterns_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _NameserverSwitcherService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/v1/switcher.proto",
}
